# Generated by Django 3.2.7 on 2021-11-22 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa_phva', models.CharField(choices=[('Planear', 'Planear'), ('Hacer', 'Hacer'), ('Verificar', 'Verificar'), ('Actuar', 'Actuar')], max_length=40, verbose_name='Etapa del phva')),
                ('actividad', models.TextField(max_length=15, verbose_name='Actividades del plan anual')),
                ('recursos', models.CharField(max_length=255, verbose_name='Recursos del plan anual')),
                ('fuente_informacion', models.CharField(max_length=255, verbose_name='Fuente de informacion del plan anual')),
                ('fecha_planeacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de planeacion')),
                ('estado_actividad', models.IntegerField(verbose_name='Estado de actividad')),
                ('nombre_archivo', models.CharField(max_length=40, verbose_name='Interpretacion de resultados')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Plan de actividades',
                'verbose_name_plural': 'Plan de actividades',
            },
        ),
        migrations.CreateModel(
            name='EquipoResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=40, verbose_name='Nombre del eqiupo')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Equipo Responsable',
                'verbose_name_plural': 'Equipo Responsable',
            },
        ),
        migrations.CreateModel(
            name='EstructuraPlanAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre de la estructura')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Estrutura Plan anual',
                'verbose_name_plural': 'Estructura plan anual',
            },
        ),
        migrations.CreateModel(
            name='PlanAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('objetivo', models.TextField(max_length=1000, verbose_name='Objetivo')),
                ('metas', models.TextField(max_length=1000, verbose_name='Metas')),
                ('alcance', models.TextField(max_length=1000, verbose_name='Alcance')),
                ('nombre_archivo', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Plan anual',
                'verbose_name_plural': 'Plan anual',
            },
        ),
        migrations.CreateModel(
            name='CumplimientoPlanAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes de la actividad,max_length=2')),
                ('porcentaje_cumplimiento', models.TextField(max_length=3, verbose_name='Metas')),
                ('fecha_cumplimiento', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de cumplimiento')),
                ('nombre_archivo', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('activo', models.BooleanField(verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plananual.actividadesplan', verbose_name='Nombre de la actividad')),
            ],
            options={
                'verbose_name': 'Cumplimiento Plan anual',
                'verbose_name_plural': 'Ejecucion de actividades',
            },
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='equipo_responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plananual.equiporesponsable', verbose_name='Identificion del equipo responsable'),
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='estructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plananual.estructuraplananual', verbose_name='Identificacion de la estructura'),
        ),
        migrations.AddField(
            model_name='actividadesplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plananual.plananual', verbose_name='Plan Anual'),
        ),
    ]
