# Generated by Django 3.2.7 on 2021-11-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenesMedicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Clasificación')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='EfectoPosible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effects_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Efecto Posible',
                'verbose_name_plural': 'Efectos Posibles',
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Fuente',
                'verbose_name_plural': 'Fuentes',
            },
        ),
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Medio',
                'verbose_name_plural': 'Medios',
            },
        ),
        migrations.AlterModelOptions(
            name='actividaespeligro',
            options={'verbose_name': 'Actividaes de peligro', 'verbose_name_plural': 'Actividaes de Peligros'},
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='c_admin',
            new_name='administrator_control',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='nc',
            new_name='consequence_level',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='nd',
            new_name='deficiency_level',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='c_ingenierie',
            new_name='engineering_control',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='ne',
            new_name='exposure_level',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='e_requirement',
            new_name='legal_requirement',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='np',
            new_name='probability_level',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='a_risk',
            new_name='risk_acceptance',
        ),
        migrations.RenameField(
            model_name='examenmedico',
            old_name='n_risk',
            new_name='risk_level',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='font',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='inp',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='inr',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='middle',
        ),
        migrations.RemoveField(
            model_name='examenmedico',
            name='sub_classification',
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='probability_level_interpretation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Interpretación nivel probabilidad'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='risk_level_interpretation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Interpretación nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenesMedicos.medio', verbose_name='Medio'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='possible_effects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenesMedicos.efectoposible', verbose_name='Efectos Posibles'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenesMedicos.fuente', verbose_name='Fuente'),
        ),
        migrations.AlterField(
            model_name='examenmedico',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examenesMedicos.clasificacion', verbose_name='Clasificación'),
        ),
    ]
