# Generated by Django 3.2.7 on 2021-11-23 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('examenesMedicos', '0002_auto_20211123_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaespeligro',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.areas', verbose_name='Area'),
        ),
    ]
