# Generated by Django 3.2.6 on 2021-11-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_indicador', models.IntegerField(choices=[('Estructura', 'Estructura'), ('Proceso', 'Proceso'), ('Resultado', 'Resultado')], verbose_name='Tipo de indicador')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tipo de Indicador',
                'verbose_name_plural': 'Tipo de indicador indicador',
            },
        ),
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del indicador')),
                ('definicion', models.CharField(max_length=15, verbose_name='Definicion del indicador')),
                ('metodo_calculo', models.CharField(max_length=255, verbose_name='Metodo de calculo')),
                ('unidad_medidad', models.CharField(max_length=255, verbose_name='Unidad de medida')),
                ('fuente_informacion', models.CharField(max_length=255, verbose_name='Fuente de informacion')),
                ('clasificacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='CLasificacion')),
                ('frecuencia_medicion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Frecuencia de medicion')),
                ('meta_anual', models.IntegerField(max_length=100, verbose_name='Meta anual')),
                ('Interpretacion_resultados', models.CharField(max_length=40, verbose_name='Interpretacion de resultados')),
                ('responsable', models.CharField(max_length=255, verbose_name='responsable')),
                ('deben_conocer_resultado', models.CharField(max_length=100, verbose_name='Deben de conocer el resultaddo')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('tipo_indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipoindicador')),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'indicador',
            },
        ),
    ]
