# Generated by Django 3.2.9 on 2021-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicadores',
            name='meta_anual',
            field=models.IntegerField(verbose_name='Meta anual'),
        ),
        migrations.AlterField(
            model_name='tipoindicador',
            name='tipo_indicador',
            field=models.CharField(choices=[('Estructura', 'Estructura'), ('Proceso', 'Proceso'), ('Resultado', 'Resultado')], max_length=15, verbose_name='Tipo de indicador'),
        ),
    ]
