# Generated by Django 3.2.7 on 2021-11-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Peligro',
                'verbose_name_plural': 'Peligros',
            },
        ),
        migrations.CreateModel(
            name='Accidentabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('inability_days', models.IntegerField(blank=True, default=0, null=True, verbose_name='Practicantes')),
                ('cie10', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cie 10')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnóstico')),
                ('accident_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descripcion accidente')),
                ('accident_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo accidente')),
                ('part_body_affected', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parte del cuerpo afectada')),
                ('accident_mechanism', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mecanismo accidente')),
                ('accident_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Agente accidente')),
                ('lesion_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de lección')),
                ('basic_cause', models.CharField(blank=True, max_length=255, null=True, verbose_name='Causa básica')),
                ('immediate_cause', models.CharField(blank=True, max_length=255, null=True, verbose_name='Causa inmediata')),
                ('intervention_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medida intervención')),
                ('compliance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cumplimiento')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado')),
                ('peligro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.peligro')),
            ],
            options={
                'verbose_name': 'Accidentabilidad',
                'verbose_name_plural': 'Accidentabilidades',
            },
        ),
    ]
