# Generated by Django 3.2.7 on 2021-11-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('accidentabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Agente de Accidente',
                'verbose_name_plural': 'Agentes de Accidentes',
            },
        ),
        migrations.CreateModel(
            name='CausaBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Causa Basica',
                'verbose_name_plural': 'Causas Basicas',
            },
        ),
        migrations.CreateModel(
            name='CausaInmediata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Causa Inmediata',
                'verbose_name_plural': 'Causas Inmediatas',
            },
        ),
        migrations.CreateModel(
            name='MecanismoAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Mecanismo de Accidente',
                'verbose_name_plural': 'Mecanismos de Accidentes',
            },
        ),
        migrations.CreateModel(
            name='ParteDelCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Parte del Cuerpo',
                'verbose_name_plural': 'Partes del Cuerpo',
            },
        ),
        migrations.CreateModel(
            name='TipoAccidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Accidente',
                'verbose_name_plural': 'Tipos de Accidentes',
            },
        ),
        migrations.CreateModel(
            name='TipoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo de Leccion',
                'verbose_name_plural': 'Tipos de Lecciones',
            },
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='compliance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cumplimiento'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='inability_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Dias de incapacidad'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='peligro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.peligro', verbose_name='Peligro'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='peligro',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='peligro',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='accident_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.agenteaccidente', verbose_name='Agente accidente'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='accident_mechanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.mecanismoaccidente', verbose_name='Mecanismo del accidente'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='accident_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.tipoaccidente', verbose_name='Tipo accidente'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='basic_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.causabasica', verbose_name='Causa basica'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='immediate_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.causainmediata', verbose_name='Causa inmediata'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='lesion_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.tipoleccion', verbose_name='Tipo lección'),
        ),
        migrations.AlterField(
            model_name='accidentabilidad',
            name='part_body_affected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accidentabilidad.partedelcuerpo', verbose_name='Parte afectada'),
        ),
    ]
