# Generated by Django 3.2.7 on 2021-11-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accidentabilidad', '0002_auto_20211120_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenteaccidente',
            old_name='name',
            new_name='agent_name',
        ),
        migrations.RenameField(
            model_name='causabasica',
            old_name='name',
            new_name='cause_name',
        ),
        migrations.RenameField(
            model_name='causainmediata',
            old_name='name',
            new_name='immediate_cause_name',
        ),
        migrations.RenameField(
            model_name='mecanismoaccidente',
            old_name='name',
            new_name='mechanism_name',
        ),
        migrations.RenameField(
            model_name='partedelcuerpo',
            old_name='name',
            new_name='body_part_name',
        ),
        migrations.RenameField(
            model_name='peligro',
            old_name='name',
            new_name='danger_name',
        ),
        migrations.RenameField(
            model_name='tipoaccidente',
            old_name='name',
            new_name='accident_type_name',
        ),
        migrations.RenameField(
            model_name='tipoleccion',
            old_name='name',
            new_name='lesson_ame',
        ),
    ]
