# Generated by Django 3.2.7 on 2021-11-13 14:12

from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comite', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipo Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre archivo')),
                ('file', models.FileField(blank=True, null=True, upload_to=documentos.models.upload_documentos_empresa)),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentos Empresa',
                'verbose_name_plural': 'Documentos Empresas',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre archivo')),
                ('file', models.FileField(blank=True, null=True, upload_to=documentos.models.upload_documentos_empleado)),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentos Empleado',
                'verbose_name_plural': 'Documentos Empleados',
            },
        ),
        migrations.CreateModel(
            name='DocumentosComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=documentos.models.upload_documentos_comite)),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comite.comite')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentos Comite',
                'verbose_name_plural': 'Documentos Comites',
            },
        ),
    ]
