# Generated by Django 3.2.7 on 2021-11-06 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipo Documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre archivo')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentos Empresa',
                'verbose_name_plural': 'Documentos Empresas',
            },
        ),
        migrations.CreateModel(
            name='DocumentosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nombre archivo')),
                ('end_date', models.DateField(auto_now_add=True, verbose_name='Fecha de vencimiento')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Documentos Empleado',
                'verbose_name_plural': 'Documentos Empleados',
            },
        ),
        migrations.CreateModel(
            name='DocumentosComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento')),
            ],
        ),
    ]
