# Generated by Django 3.2.7 on 2021-11-06 21:54

from django.db import migrations, models
import documentos.models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=documentos.models.custom_upload_to),
        ),
    ]
