# Generated by Django 3.2.6 on 2021-11-13 16:58

from django.db import migrations, models
import django.db.models.deletion
import proveedor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos_PP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre EPP')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=proveedor.models.custom_upload_to)),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Elementos de Proteccion Personal',
                'verbose_name_plural': 'Elementos de Proteccion Personal',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('nit', models.CharField(max_length=30, unique=True, verbose_name='Nit')),
                ('certificador_arl', models.CharField(max_length=255, verbose_name='Certificado ARL')),
                ('es_autorizado', models.BooleanField(verbose_name='Es Autorizado')),
                ('seguridad_social', models.CharField(max_length=30, verbose_name='Seguridad Social')),
                ('ficha_seg_productos', models.CharField(max_length=255, verbose_name='Ficha Productos')),
                ('telefono1', models.CharField(max_length=30, verbose_name='Telefono 1')),
                ('telefono2', models.CharField(max_length=30, verbose_name='Telefono 2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipoempresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Elementos_Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida_util', models.IntegerField(verbose_name='Meses de Vida Util')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('id_elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.elementos_pp')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'verbose_name': 'Elementos Proveedor',
                'verbose_name_plural': 'Elementos Proveedor',
            },
        ),
    ]
