# Generated by Django 3.2.7 on 2021-11-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementos_pp',
            options={'verbose_name': 'Elementos de Proteccion Personal', 'verbose_name_plural': 'Elementos de Proteccion Personal'},
        ),
        migrations.AlterModelOptions(
            name='elementos_proveedor',
            options={'verbose_name': 'Elementos Proveedor', 'verbose_name_plural': 'Elementos Proveedor'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='elementos_pp',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='elementos_proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
