# Generated by Django 3.2.8 on 2021-11-06 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('factura', models.CharField(max_length=255, verbose_name='Factura')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('valor_sin_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Sin IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor IVA')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Factutra',
                'verbose_name_plural': 'Factutras',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(max_length=4, verbose_name='Año')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
            },
        ),
        migrations.CreateModel(
            name='CronogramaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, verbose_name='Actividad')),
                ('observaciones', models.TextField(verbose_name='Observaciones')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Presupuesto')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.periodo', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
