# Generated by Django 3.2.6 on 2021-10-05 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=registration.models.custom_upload_to, null=True, blank=True)),
                ('telefono', models.CharField(max_length=20, verbose_name="Telefono", null=True, blank=True)),
                ('celular', models.CharField(max_length=20, verbose_name="Celular", null=True, blank=True)),
                ('direccion', models.CharField(max_length=255,verbose_name="Direccion", null=True, blank=True)),
                ('profesion', models.CharField(max_length=255,verbose_name="Profesion", null=True, blank=True)),
                ('cedula', models.CharField(max_length=20,verbose_name="Cedula", null=True, blank=True)),
                ('genero', models.CharField(max_length=20, choices=registration.models.Generos,verbose_name="Genero",default="Otro")),
                ('fecha_nacimiento', models.DateField(verbose_name="Fecha Nacimiento",null=False,blank=False)),
                ('estado_civil', models.CharField(max_length=20, choices=registration.models.EstaCivil,verbose_name="Estado Civil",default="No indica")),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['usuario__username'],
            },
        ),
    ]
