# Generated by Django 3.2.7 on 2021-11-22 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion')),
                ('profesion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profesion')),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cedula')),
                ('genero', models.CharField(choices=[('Femenino', 'F'), ('Masculino', 'M'), ('Otro', 'Otro')], default='Otro', max_length=20, verbose_name='Genero')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('estado_civil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Union Libre', 'Union Libre'), ('Viudo', 'Viudo'), ('No indica', 'No indica')], default='No indica', max_length=20, verbose_name='Estado Civil')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Contacto_Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto Emergencia')),
                ('parentesco_emergercia', models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Hermano(a)', 'Hermano(a)'), ('Primo(a)', 'Primo(a)'), ('Tio(a)', 'Tio(a)'), ('Abuelo(a)', 'Abuelo(a)'), ('Hermano(a)', 'Hermano(a)'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Parentesco')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Emergencia')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
            },
        ),
    ]
