# Generated by Django 3.2.6 on 2021-11-03 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0002_auto_20211026_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='profile',
            name='modify_at',
            field=models.DateField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha Nacimiento'),
        ),
        migrations.CreateModel(
            name='Contacto_Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto Emergencia')),
                ('parentesco_emergercia', models.CharField(blank=True, choices=[('Mamá', 'Mamá'), ('Papá', 'Papá'), ('Hermano(a)', 'Hermano(a)'), ('Primo(a)', 'Primo(a)'), ('Tio(a)', 'Tio(a)'), ('Abuelo(a)', 'Abuelo(a)'), ('Hermano(a)', 'Hermano(a)'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Parentesco')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono Emergencia')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['usuario__username'],
            },
        ),
    ]
