# Generated by Django 3.2.7 on 2021-11-13 22:06

import capacitaciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.CharField(max_length=255, null=True, verbose_name='Justificacion')),
                ('alcance', models.CharField(max_length=255, null=True, verbose_name='Alcance')),
                ('objetivo', models.CharField(max_length=255, null=True, verbose_name='Objetivo')),
                ('indicadores', models.CharField(max_length=255, null=True, verbose_name='Indicadores')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.periodo')),
            ],
            options={
                'verbose_name_plural': 'Plan de Capacitacion',
            },
        ),
        migrations.CreateModel(
            name='Capacitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255, verbose_name='Tema')),
                ('area', models.CharField(max_length=255, verbose_name='Area del Empleado')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('meses', models.CharField(choices=[('Enero', '1'), ('Febrero', '2'), ('Marzo', '3'), ('Abril', '4'), ('Mayo', '5'), ('Junio', '6'), ('Julio', '7'), ('Agosto', '8'), ('Septiembre', '9'), ('Octubre', '10'), ('Noviembre', '11'), ('Diciembre', '12')], max_length=20, verbose_name='Estado Civil')),
                ('archivo_soporte', models.FileField(blank=True, null=True, upload_to=capacitaciones.models.soporte_capacitacion_upload_to)),
                ('fecha_planeacion', models.DateField(verbose_name='Fecha de Planeacion')),
                ('fecha_cumplimiento', models.DateField(verbose_name='Fecha de Cumplimiento')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('id_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capacitaciones.plan_capacitacion')),
            ],
            options={
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
    ]
