# Generated by Django 3.2.6 on 2021-10-27 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=255, verbose_name='Nombre Area')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Nombre Area',
                'verbose_name_plural': 'Areas de la empresa',
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('salario_cargo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Empresa')),
                ('nit', models.CharField(max_length=15, verbose_name='NIT')),
                ('actividad', models.CharField(max_length=255, verbose_name='Actividad Económica')),
                ('nivel_riesgo', models.CharField(max_length=255, verbose_name='Nivel de Riesgo')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=255, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=255, verbose_name='Departamento')),
                ('naturaleza_empresa', models.CharField(max_length=100, verbose_name='Naturaleza jurídica')),
                ('telefonos', models.CharField(max_length=40, verbose_name='Teléfonos de contacto')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo electrónico')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de empresa')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=255, verbose_name='Nivel Académico')),
            ],
            options={
                'verbose_name': 'Nivel Académico',
                'verbose_name_plural': 'Niveles Académicos',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, verbose_name='Código de Empleado')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('salario_basico', models.IntegerField(verbose_name='Salario')),
                ('arl', models.CharField(max_length=100, verbose_name='ARL')),
                ('ssp', models.CharField(max_length=100, verbose_name='EPS')),
                ('sss', models.CharField(max_length=100, verbose_name='Fondo Pensiones')),
                ('cuenta_bancaria', models.CharField(max_length=20, verbose_name='Número de cuenta')),
                ('create_at', models.DateField(auto_now_add=True, null=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.areas')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.cargos')),
                ('nivel_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.nivelacademico')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.AddField(
            model_name='areas',
            name='nit_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa'),
        ),
    ]
