# Generated by Django 3.2.6 on 2021-10-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='cargos',
            name='salario_cargo',
            field=models.IntegerField(default=0, verbose_name='Salario'),
        ),
    ]
