# Generated by Django 3.2.8 on 2021-11-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='antiguedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Tiempo en la empresa'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='barrio',
            field=models.CharField(default='No indicado', max_length=255, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ciudad',
            field=models.CharField(default='No indicada', max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cual_enfermedad',
            field=models.CharField(default='No indicada', max_length=255, verbose_name='Que enfermedad Sufre?'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cual_medicamento',
            field=models.CharField(default='No indicado', max_length=255, verbose_name='Que Medicamento toma?'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default='No indicado', max_length=255, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estrato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_retiro',
            field=models.DateField(default='No indicado', verbose_name='Fecha de Retiro'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sufre_enfermedad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No indicado', max_length=255, verbose_name='Sufre Alguna Enfermedad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_contrato',
            field=models.CharField(choices=[('Fijo', 'Fijo'), ('Indefinido', 'Indefinido'), ('Obra Labor', 'Obra Labor'), ('Otro', 'Otro')], default='No indicado', max_length=255, verbose_name='Tipo Contrato'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='toma_medicamentos',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No indicado', max_length=255, verbose_name='Toma Medicamentos?'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(default='No indicada', max_length=255, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(default='No indicado', max_length=255, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='sanidad',
            name='pandemia',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=255, verbose_name='Es Pandemia?'),
        ),
    ]
