# Generated by Django 3.2.8 on 2021-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='antiguedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiempo en la empresa'),
        ),
    ]
