# Generated by Django 3.2.8 on 2021-11-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empleado_antiguedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='antiguedad',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.tipoempresa', verbose_name='Tipo Empresa'),
        ),
    ]
