# Generated by Django 3.2.6 on 2021-11-06 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211106_1411'),
        ('empresa', '0002_tipoempresa'),
    ]

    operations = [
    ]
