# Generated by Django 3.2.8 on 2021-10-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211025_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsabilidad', models.TextField(blank=True, null=True, verbose_name='Responsabilidad')),
            ],
            options={
                'verbose_name': 'Responsabiliad',
                'verbose_name_plural': 'Responsabiliades',
            },
        ),
        migrations.AlterField(
            model_name='cargos',
            name='salario_cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_basico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario'),
        ),
    ]
