# Generated by Django 3.2.6 on 2021-11-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20211026_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsabilidades',
            name='create_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creado el'),
        ),
        migrations.AddField(
            model_name='responsabilidades',
            name='modify_at',
            field=models.DateField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='cargos',
            name='salario_cargo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
