# Generated by Django 3.2.8 on 2021-11-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20211120_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='ccf',
            field=models.CharField(default='N/A', max_length=100, verbose_name='Caja de Compensación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cual_enfermedad',
            field=models.CharField(default='N/A', max_length=255, verbose_name='Que enfermedad Sufre?'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cual_medicamento',
            field=models.CharField(default='N/A', max_length=255, null=True, verbose_name='Que Medicamento toma?'),
        ),
        migrations.AlterField(
            model_name='tipoempresa',
            name='tipo_empresa',
            field=models.CharField(max_length=200, verbose_name='Tipo de Empresa'),
        ),
    ]
