# Generated by Django 3.2.7 on 2021-11-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_cargos_salario_cargo'),
        ('empresa', '0004_auto_20211120_1532'),
    ]

    operations = [
    ]
