# Generated by Django 3.2.7 on 2021-11-13 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividaesPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=250, null=True, verbose_name='Proceso')),
                ('area', models.CharField(blank=True, max_length=250, null=True, verbose_name='Area')),
                ('routine', models.BooleanField(default=False, verbose_name='Es rutinario')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
            ],
            options={
                'verbose_name': 'Actividaes Peligro',
                'verbose_name_plural': 'Actividaes Peligros',
            },
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(blank=True, max_length=250, null=True, verbose_name='Clasificación')),
                ('sub_classification', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sub Clasificación')),
                ('effects', models.CharField(blank=True, max_length=250, null=True, verbose_name='Efectos posibles')),
                ('font', models.CharField(blank=True, max_length=250, null=True, verbose_name='Fuentes')),
                ('middle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Medio')),
                ('individual', models.CharField(blank=True, max_length=250, null=True, verbose_name='Individuo')),
                ('nd', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nivel de deficiencia')),
                ('ne', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nivel de exposición')),
                ('np', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nivel de probabilidad')),
                ('inp', models.CharField(blank=True, max_length=250, null=True, verbose_name='Interpretación np')),
                ('nc', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nivel de concecuencia')),
                ('n_risk', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nivel de riesgo')),
                ('a_risk', models.IntegerField(blank=True, default=0, null=True, verbose_name='Aceptación riesgo')),
                ('plant', models.IntegerField(blank=True, default=0, null=True, verbose_name='Planta')),
                ('mission', models.IntegerField(blank=True, default=0, null=True, verbose_name='Mision')),
                ('contractors', models.IntegerField(blank=True, default=0, null=True, verbose_name='Contratistas')),
                ('practitioners', models.IntegerField(blank=True, default=0, null=True, verbose_name='Practicantes')),
                ('inr', models.CharField(blank=True, max_length=250, null=True, verbose_name='Interpretación nr')),
                ('worst_concecuence', models.CharField(blank=True, max_length=250, null=True, verbose_name='Peor concecuencia')),
                ('e_requirement', models.CharField(blank=True, max_length=250, null=True, verbose_name='Existencia requisito legal')),
                ('elimination', models.CharField(blank=True, max_length=250, null=True, verbose_name='Eliminación')),
                ('substitution', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sustitución')),
                ('c_ingenierie', models.CharField(blank=True, max_length=250, null=True, verbose_name='Control ingenieria')),
                ('c_admin', models.CharField(blank=True, max_length=250, null=True, verbose_name='Control administrador')),
                ('equipment_elements_pp', models.CharField(blank=True, max_length=250, null=True, verbose_name='Equipo elementos pp')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('activitie_danger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes_medicos.actividaespeligro')),
            ],
            options={
                'verbose_name': 'Examen Medico',
                'verbose_name_plural': 'Examenes Medicos',
            },
        ),
    ]
