# Generated by Django 3.2.7 on 2021-11-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividaespeligro',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='examenmedico',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
