# Generated by Django 3.2.8 on 2021-11-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=4, verbose_name='Código CIE 10')),
                ('grupo', models.TextField(verbose_name='Grupo de Diagnóstico')),
                ('descripcion', models.TextField(verbose_name='Descripción de Diagnóstico')),
            ],
        ),
        migrations.CreateModel(
            name='Incapacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=30, verbose_name='Mes')),
                ('origen', models.CharField(max_length=155, verbose_name='Origen')),
                ('clasificacion', models.CharField(max_length=155, verbose_name='Clasificación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalzaición')),
                ('total_incapacidad', models.IntegerField(verbose_name='Total días incapacidad')),
                ('valor_incapacidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Incapacidad')),
                ('valor_asumido_empresa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Asumido Empresa')),
                ('valor_asumido_eps', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Asumido EPS')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('modify_at', models.DateField(auto_now=True, verbose_name='Actualizado el')),
            ],
        ),
    ]
