# Generated by Django 3.2.8 on 2021-11-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ausentismos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cie10',
            options={'verbose_name': 'Diagnostico', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterModelOptions(
            name='incapacidades',
            options={'verbose_name': 'Incapacidad', 'verbose_name_plural': 'Incapacidades'},
        ),
    ]
