# Generated by Django 3.2.8 on 2021-11-13 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('ausentismos', '0002_incapacidades_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidades',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado'),
        ),
    ]
