# Generated by Django 3.2.6 on 2021-11-03 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombcomite', models.CharField(max_length=200, verbose_name='Nombre de Comite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comite',
                'verbose_name_plural': 'Comite',
            },
        ),
        migrations.CreateModel(
            name='RolComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rol', models.CharField(max_length=200, verbose_name='Rol de Comite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol Comite',
                'verbose_name_plural': 'Rol Comite',
            },
        ),
        migrations.CreateModel(
            name='ParticipantesComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comite.comite')),
                ('empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empleado')),
                ('rol_comite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comite.rolcomite')),
            ],
        ),
    ]
