# Generated by Django 3.2.9 on 2021-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='comite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificacion'),
        ),
        migrations.AlterField(
            model_name='rolcomite',
            name='tipo_rol',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Secretario', 'Secretario'), ('Miembro', 'Miembro'), ('Suplente', 'Suplente')], max_length=20, verbose_name='Rol de Comite'),
        ),
    ]
